### ISSUE TITLE
Game session returns forbidden

### ISSUE THREAD

**Issue by TJRoh01** [kweimann/cruiser#1]
First of all, very cool project! Good job :)

When I try to start the bot I get this:

```
Traceback (most recent call last):
  File "start_bot.py", line 68, in <module>
    client.login()
  File "/home/tomas/Dev/git/cruiser/ogame/game/client.py", line 117, in login
    game_sess = self._get_game_session(game_env_id, platform_game_id)
  File "/home/tomas/Dev/git/cruiser/ogame/game/client.py", line 723, in _get_game_session
    raise ValueError(game_sess['error'])
ValueError: {'message': 'Forbidden'}
```

Any idea how to solve it?

**Comment by TJRoh01** [comment]
Found the problem!

Apparently it gets the locale in the config wrong and instead of making a get_game_session request with "en_US" it does "us_US".

**Comment by TJRoh01** [comment]
And it gets it wrong because OGame has "us" instead of "en_US" as a language (yes, I speak american).

**Comment by kweimann** [comment]
Thanks for the PR. Merged!

**Comment by TJRoh01** [comment]
You're welcome :+1:
